<?php

use Zend\Escaper\Escaper;

$escaper = new Escaper('utf-8');
$form = $this->form;
$form->setAttribute('id', 'div_form');
$form->prepare();
?>
<script>
    //#############################################################
    //#############################################################
    //##
    //##    Read data customerid into javascript context, taking
    //##    care to escape the value - just in case ;).
    //##
    //#############################################################
    //#############################################################
    var php_var = "<?= $escaper->escapeHtml($this->customerid) ?>";

    //#############################################################
    //#############################################################
    //##
    //##    Datatables API reference scoped for top-level access. 
    //##
    //#############################################################
    //#############################################################
    var $API;

    //#############################################################
    //#############################################################
    //##
    //##    Convenience function to get a human readable date string.
    //##
    //#############################################################
    //#############################################################
    var getPrettyTime = function () {
        var objToday = new Date(),
                weekday = new Array('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'),
                dayOfWeek = weekday[objToday.getDay()],
                domEnder = function () {
                    var a = objToday;
                    if (/1/.test(parseInt((a + "").charAt(0))))
                        return "th";
                    a = parseInt((a + "").charAt(1));
                    return 1 === a ? "st" : 2 === a ? "nd" : 3 === a ? "rd" : "th"
                }(),
                dayOfMonth = today + (objToday.getDate() < 10) ? '0' + objToday.getDate() + domEnder : objToday.getDate() + domEnder,
                months = new Array('January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'),
                curMonth = months[objToday.getMonth()],
                curYear = objToday.getFullYear(),
                curHour = objToday.getHours() > 12 ? objToday.getHours() - 12 : (objToday.getHours() < 10 ? "0" + objToday.getHours() : objToday.getHours()),
                curMinute = objToday.getMinutes() < 10 ? "0" + objToday.getMinutes() : objToday.getMinutes(),
                curSeconds = objToday.getSeconds() < 10 ? "0" + objToday.getSeconds() : objToday.getSeconds(),
                curMeridiem = objToday.getHours() > 12 ? "PM" : "AM";
        var today = curHour + ":" + curMinute + "." + curSeconds + curMeridiem + " " + dayOfWeek + " " + dayOfMonth + ", " + curMonth + " " + curYear;
        return today;
    };

    //#############################################################
    //#############################################################
    //##
    //##    OverridePrice button click handler.
    //##    Sends REST GET to Ajax Endpoint. The Endpoint
    //##    inserts the override price record into the db
    //##    and returns the results - which we grab on callback
    //##    and populate the table with the values that were submitted. 
    //##
    //#############################################################
    //#############################################################
    var submitOverride = function (rowIdx, sku) {
        var overrideprice = $("#overrideprice").val();
        var comment = $("#comment").val();
        var option = $("#option").val();
        $.getJSON("ajax/items?customerid=<?= $escaper->escapeHtml($this->customerid) ?>&customername=<?= $escaper->escapeHtml($this->customername) ?>&action=overridePrice&index=" + rowIdx + "&sku=" + sku + "&overrideprice=" + overrideprice + "&comment=" + comment + "&option=" + option + "", function (data) {
            overrideCallback(data);
        });
        return false;
    };

    //#############################################################
    //#############################################################
    //##
    //##    Callback on Successful Ajax Call to add a row to the table.
    //##
    //#############################################################
    //#############################################################
    var appendRowToTable = function (data) {
        if (data.success) {
            $API.row.add({
                "productname": data['productname'],
                "shortescription": data['shortescription'],
                "comment": data['comment'],
                "option": data['option'],
                "qty": data['qty'],
                "wholesale": data['wholesale'],
                "retail": data['retail'],
                "overrideprice": data['overrideprice'],
                "uom": data['uom'],
                "sku": data['sku'],
                "status": data['status'] === '1' ? 'Enabled' : 'Disabled',
                "saturdayenabled": data['saturdayenabled'] === '1' ? 'Enabled' : 'Disabled'
            }).draw(false);
            $('.modal').modal('hide');
        } else {
            console.log('Row NOT added response: ' + JSON.stringify(data));
        }
    };

    //#############################################################
    //#############################################################
    //##
    //##    Callback on Successful Ajax Call to override a price.
    //##
    //#############################################################
    //#############################################################
    var overrideCallback = function (data) {
        if (data.success) {
            //price has been successfully overridden into DB
            //now update the values in the table to reflect the override.
            //set the overrideprice on the selected row - then redraw
            //the table to cause the appropriate renderers to handle
            //the override display.
            var rowIdx = data.index;
            var rowData = $API.row(rowIdx).data();
            rowData['overrideprice'] = data.overrideprice;
            rowData['comment'] = data.comment;
            rowData['option'] = data.option;
            $API.row(rowIdx).data(rowData);
            $API.draw(false);
            $('.modal').modal('hide');
        } else {
            console.log('Error occurred trying to overrideprice: ' + JSON.stringify(data));
        }
    };

    //#############################################################
    //#############################################################
    //##
    //##    Document Ready Event Handler
    //##
    //#############################################################
    //#############################################################
    $(document).ready(function () {
        $API = $('#customerlisttable').DataTable({
            "ajax": '/ajax/items?action=customerlisttableget&customerid=' + php_var,
            //#############################################################
            //#############################################################
            //##
            //##    Datatables columnDefs with appropriate renderers.
            //##
            //#############################################################
            //#############################################################
            "columns": [
                {"data": "productname"},
                {"data": "shortescription"},
                {"data": "comment"},
                {"data": "option"},
                {"data": "qty"},
                {"data": "wholesale",
                    "render": function (data, type, row, meta) {
                        if (data) {
                            var result = "$";
                            return result + row['wholesale'];
                        } else {
                            return  '';
                        }
                    }},
                {"data": "retail",
                    "render": function (data, type, row, meta) {
                        var enabled = row['status'] === 'Enabled';
                        var overrideprice = row['overrideprice'];
                        if (enabled && data && !overrideprice) {
                            var result = "$";
                            return result + row['retail'];
                        } else if (overrideprice) {
                            var result = "$";
                            return result + overrideprice;
                        }
                        if (!enabled) {
                            return  'Call for availability';
                        }
                        return data;
                    }
                },
                {"data": "overrideprice", "visible": false,
                    "render": function (data, type, row, meta) {
                        if (data) {
                            var result = "$";
                            return result + data;
                        } else {
                            return  data;
                        }
                        return data;
                    }
                },
                {"data": "uom"},
                {"data": "sku"},
                {"data": "status",
                    "render": function (data, type, row, meta) {
                        var result = "";
                        if (row['status']) {
                            result = data;
                        } else {
                            result = '<p class="bg-warning">Out of Stock</p>';
                        }
                        return result;
                    }},
                {"data": "saturdayenabled",
                    "render": function (data, type, row, meta) {
                        var result = "";
                        if (row['saturdayenabled']) {
                            result = 'On <button class="btn btn-primary deleteMe"><span class="glyphicon glyphicon-minus"></span></button>';
                        } else {
                            result = 'Off <button class="btn btn-primary deleteMe"><span class="glyphicon glyphicon-minus"></span></button>';
                        }
                        return result;
                    }
                }
            ],
            //#############################################################
            //#############################################################
            //##
            //##    Datables RowCallback executed on every row.
            //##    Checks if row.status = Enabled OR if 
            //##    row.overrideprice is set - in which case, we
            //##    lift the requirement whereby we grey out every 
            //##    Disabled row because if the overrideprice has a
            //##    value - then the Salesperson has called in and 
            //##    overridden it.
            //##
            //#############################################################
            //#############################################################
            rowCallback: function (row, data, index) {
                if (data.status !== 'Enabled' && !data.overrideprice) {
                    $(row).attr('class', 'ffm-table-disabled');
                }
            },
            //#############################################################
            //#############################################################
            //##
            //##    Datatables Responsive Plugin
            //##
            //#############################################################
            //#############################################################
            responsive: {
                details: {
                    display: $.fn.dataTable.Responsive.display.modal({
                        header: function (row) {
                            var data = row.data();
                            return data['productname'] + ' <div class="pull-right"><span>' + data['sku'] + '</span><span><button type="button" class="close" data-dismiss="modal">&times;</button></span></div>';
                        }
                    }),
                    renderer: function (api, rowIdx, columns) {
                        //handle case where item is disabled!
                        var comments = columns[2].data;
                        var options = columns[3].data;
                        var sku = columns[9].data;
                        var status = columns[10].data;
                        var data = '';
                        //#############################################################
                        //#############################################################
                        //##
                        //##    IF row.status = Disabled
                        //##    Allow Price Override, but warn the Salesperson.
                        //##
                        //#############################################################
                        //#############################################################
                        if (status && status === 'Disabled') {
                            data += '<div class="row">';
                            data += '       <div class="col-md-12">';
                            data += '           <div class="ffm-callout ffm-callout-error">\n\
                                                    <h4 >Notice <small class="pull-right">You must call first.</small></h4>\n\
                                                    <hr/>\n\
                                                    <p>\n\
                                                        This item is marked Out Of Stock. Please call for availability.\n\
                                                    </p>\n\
                                                </div>';
                            data += '       </div>';
                            data += '</div>';
                        }
                        data += '   <div class="row">';
                        data += '       <div class="col-md-12">';
                        data += '           <form id="override_form" class="form" action="#" >';
                        data += '               <div class="row form-group">\n\
                                                    <div class="col-md-4">\n\
                                                        <label for="overrideprice">\n\
                                                            <span style="color:red;">*</span>&nbsp;<i>Override Price</i> \n\
                                                        </label>\n\
                                                    </div>\n\
                                                    <div class="col-md-4">\n\
                                                        <div class="input-group">\n\
                                                            <div class="input-group-addon">$</div>\n\
                                                            <input type="text" class="form-control" id="overrideprice" aria-describedby="priceHelpInline" placeholder="Price">\n\
                                                        </div>\n\
                                                    </div>\n\
                                                    \n\
                                                    <div class="col-md-4">\n\
                                                        <small id="priceHelpInline" class="text-muted"> -- Enter Price Override.</small>\n\
                                                    </div>\n\
                                                </div>';
                        data += '               <div class="row form-group">\n\
                                                    <div class="col-md-4">\n\
                                                        <label for="comment">\n\
                                                            Comments\n\
                                                        </label>\n\
                                                    </div>\n\
                                                    <div class="col-md-4">\n\
                                                        <input type="textarea" class="form-control" id="comment" value="' + comments + '" aria-describedby="commentHelpInline" placeholder="Comments">\n\
                                                    </div>\n\
                                                    \n\
                                                    <div class="col-md-4">\n\
                                                        <small id="commentHelpInline" class="text-muted"> -- Enter/Edit Comment.</small>\n\
                                                    </div>\n\
                                                </div>';
                        data += '               <div class="row form-group">\n\
                                                    <div class="col-md-4">\n\
                                                        <label for="option">\n\
                                                            Option\n\
                                                        </label>\n\
                                                    </div>\n\
                                                    <div class="col-md-4">\n\
                                                        <input type="textarea" class="form-control" id="option" value="' + options + '" aria-describedby="optionHelpInline" placeholder="Options">\n\
                                                    </div>\n\
                                                    \n\
                                                    <div class="col-md-4">\n\
                                                        <small id="optionHelpInline" class="text-muted"> -- Enter/Edit Option.</small>\n\
                                                    </div>\n\
                                                </div>';
                        data += '               <div class="row form-group">';

                        //#############################################################
                        //#############################################################
                        //##
                        //##    Override Price Click Handler.
                        //##
                        //#############################################################
                        //#############################################################
                        data += '                       <div class="col-md-4 col-md-offset-8">\n\
                                                            <span class="pull-right">\n\
                                                                <button type="submit" onclick=\'return submitOverride(' + rowIdx + ', ' + sku + ');\' \n\
                                                                        data-toggle="tooltip" data-placement="top" title="Submit Price Override" class="btn btn-default">\n\
                                                                    Override\n\
                                                                </button>\n\
                                                            </span>\n\
                                                    </div>\n\
                                                </div>';
                        data += '           </form>';
                        data += '       </div>';
                        data += '   </div>';
                        data += '<div class="row">\n\
                                        <div class="col-md-12">\n\
                                            <div class="list-group">';
                        data += $.map(columns, function (col, i) {
                            return '            <div class="list-group-item" data-dt-row="' + col.rowIndex + '" data-dt-column="' + col.columnIndex + '">' +
                                    '           <h5><small>' + columns[i].title + '</small><span class="pull-right">' + columns[i].data + '</span></h5>' +
                                    '       </div>';
                        }).join('');
                        data += '           </div>\n\
                                        </div>\n\
                                    </div>';
                        return $(data);
                    }
                }
            },
            dom: 'Bfrtip',
            //#############################################################
            //#############################################################
            //##
            //##    Datatables Buttons Plugin.
            //##    pdfHtml5 Button creates PDF.
            //##    add-row Button allows Salesperson to add a row to 
            //##    the table.
            //##
            //#############################################################
            //#############################################################
            buttons: [
                {
                    extend: 'pdfHtml5',
                    customize: function (doc) {
                        doc.content.forEach(function (row) {
                            if (row['table'] && row['table']['body']) {
                                var newRowData = [];
                                var idx = 0;
                                row['table']['body'].forEach(function (rowdata) {
                                    //product,  description, comments, UOM, SKU, Retail price or Inserted price.
                                    //remove idx: 3-7
                                    if (idx++ === 0) {
                                        //add our customized Header Row.
                                        var head = JSON.parse('[{"text": "Product","style": "tableHeader"}, {"text": "Description","style": "tableHeader"}, {"text": "Comment","style": "tableHeader"}, {"text": "UOM","style": "tableHeader"}, {"text": "SKU","style": "tableHeader"}, {"text": "Price","style": "tableHeader"}]');
                                        newRowData.push(head);
                                    } else {
                                        var row = [];
                                        row.push(rowdata[0]);
                                        row.push(rowdata[1]);
                                        row.push(rowdata[2]);
                                        row.push(rowdata[8]);
                                        row.push(rowdata[9]);
                                        var override = rowdata[7].text;
                                        if (override) {
                                            row.push(rowdata[7]);
                                        } else {
                                            row.push(rowdata[6]);
                                        }

                                        //only add this row if Price
                                        if (override || rowdata[6].text.indexOf('Call') === -1) {
                                            newRowData.push(row);
                                        }
                                    }
                                });
                                row['table']['body'] = newRowData;
                            }
                        });
                        var today = getPrettyTime();
                        doc.content.splice(1, 0, {
                            margin: [0, 0, 0, 12],
                            alignment: 'right',
                            //add User's name to report.
                            text: 'Creator: <?= $this->salesperson ?> (<?= $this->salespersonid ?>)     Customer: <?= $this->customername ?> (<?= $this->customerid ?>)      ' + today
                        });
                    }
                },
                {
                    text: 'Add Product',
                    className: 'ffm-custom-append'
                }
            ]
        });
        //#############################################################
        //#############################################################
        //##
        //##    REMOVE Table Row.
        //##    Remove button added to each table row. 
        //##    Removes the row after sending an AJAX GET call 
        //##    with query params specifying customerid and
        //##    sku and action. Then the AbstractRestful ItemsController
        //##    Endpoint handles the request and adds the removedSKU
        //##    to session scope [customerid][removedSKUS]=[$skus1Dim]
        //##    so even if the Salesperson navigates to other customers
        //##    and prints other PDF's, as long as they stay logged-in
        //##    and do not press the logout button -> The removed rows
        //##    are always respected and override the svc GET calls.
        //##    @see \Ajax\Service\Sales\ItemsFilterTableArrayService.
        //##
        //#############################################################
        //#############################################################
        $('body').on('click', '.deleteMe', function () {
            //first make ajax call to ItemsController to add the removedSKU to session
            //then remove the row and call draw after the call returns
            var sku = $(this).parent().parent().parent("div").prev().prev().find('.pull-right').html();
            var idx = $(this).parent().parent().parent("div").attr('data-dt-row');
            console.log('SKU: ' + sku + ' Idx: ' + idx);
            $.getJSON('ajax/items?action=removeRow&sku=' + sku + '&customerid=' + php_var, function () {
                console.log("REST Call made.");
            }).done(function () {
                console.log('Ajax call successful with sku: ' + sku);
                $API.row(idx).remove().draw();
                $('.modal').modal('hide');
            }).fail(function () {
                console.log("REST Call failed.");
            });
        });
        //#############################################################
        //#############################################################
        //##
        //##    INIT Function called after itemsTable.draw();
        //##    This will add necessary data-*-attr's for the
        //##    ffm-custom-append Button added to the Datatables
        //##    options.
        //##
        //#############################################################
        //#############################################################
        $API.on('init.dt', function (e, settings, json) {
            //##########  Custom Datatables Buttons Impl ##############
            //this is used to add data-* attributes to datatables buttons.
            //the button is initialized
            var api = new $.fn.dataTable.Api(settings);
            if (api.buttons().length > 0) {
                $("a", api.buttons().container(0)).each(function (index) {
                    if ($(this).hasClass('ffm-custom-append')) {
                        $(this).attr('data-target', '#addProductModal');
                        $(this).attr('data-toggle', 'modal');
                    }
                });
            }
            //##########  END Custom Datatables Buttons Impl ##############
        });
    });

</script>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            &nbsp;
        </div>
        <div class="col-md-12">
            <nav class="breadcrumb">
                <?php if (isset($_SESSION["roles"])): ?>
                    <?php if ($_SESSION["roles"][0]->getRole() == "admin"): ?>
                        <li>
                            <a href="/sales">Salespeople</a>
                        </li>
                    <?php endif; ?>
                <?php endif; ?>
                <li><a href="/users">Customers</a></li>
                <li class="active">Products</li>
            </nav>
            <div class="ffm-callout ffm-callout-warning">
                <h4 >Products <small class="pull-right"><?= $this->customername ?></small></h4>
                <hr/>
                <p>Please make selections for your customer.</p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="modal fade" id="addProductModal" role="dialog">
                <div class="modal-dialog">
                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">Add Product</h4>
                        </div>
                        <div class="modal-body">
                            <?= $this->form()->openTag($form); ?> 
                            <div class="form-group">
                                <?= $this->formLabel($form->get('product')) ?>
                                <?= $this->formElement($form->get('product')) ?>
                                <?= $this->formElementErrors()->render($form->get('product'), ['class' => 'help-block']) ?>
                            </div>
                            <div class="form-group">
                                <?= $this->formLabel($form->get('description')) ?>
                                <?= $this->formElement($form->get('description')) ?>
                                <?= $this->formElementErrors()->render($form->get('description'), ['class' => 'help-block']) ?>
                            </div>
                            <div class="form-group">
                                <?= $this->formLabel($form->get('comment')) ?>
                                <?= $this->formElement($form->get('comment')) ?>
                                <?= $this->formElementErrors()->render($form->get('comment'), ['class' => 'help-block']) ?>
                            </div>
                            <div class="form-group">
                                <?= $this->formLabel($form->get('option')) ?>
                                <?= $this->formElement($form->get('option')) ?>
                                <?= $this->formElementErrors()->render($form->get('option'), ['class' => 'help-block']) ?>
                            </div>
                            <div class="form-group">
                                <?= $this->formLabel($form->get('qty')) ?>
                                <?= $this->formElement($form->get('qty')) ?>
                                <?= $this->formElementErrors()->render($form->get('qty'), ['class' => 'help-block']) ?>
                            </div>
                            <div class="form-group">
                                <?= $this->formLabel($form->get('wholesale')) ?>
                                <?= $this->formElement($form->get('wholesale')) ?>
                                <?= $this->formElementErrors()->render($form->get('wholesale'), ['class' => 'help-block']) ?>
                            </div>
                            <div class="form-group">
                                <?= $this->formLabel($form->get('retail')) ?>
                                <?= $this->formElement($form->get('retail')) ?>
                                <?= $this->formElementErrors()->render($form->get('retail'), ['class' => 'help-block']) ?>
                            </div>
                            <div class="form-group">
                                <?= $this->formLabel($form->get('overrideprice')) ?>
                                <?= $this->formElement($form->get('overrideprice')) ?>
                                <?= $this->formElementErrors()->render($form->get('overrideprice'), ['class' => 'help-block']) ?>
                            </div>
                            <div class="form-group">
                                <?= $this->formLabel($form->get('uom')) ?>
                                <?= $this->formElement($form->get('uom')) ?>
                                <?= $this->formElementErrors()->render($form->get('uom'), ['class' => 'help-block']) ?>
                            </div>
                            <div class="form-group">
                                <?= $this->formLabel($form->get('sku')) ?>
                                <?= $this->formElement($form->get('sku')) ?>
                                <?= $this->formElementErrors()->render($form->get('sku'), ['class' => 'help-block']) ?>
                            </div>
                            <div class="form-group">
                                <?= $this->formLabel($form->get('status')) ?>
                                <?= $this->formElement($form->get('status')) ?>
                                <?= $this->formElementErrors()->render($form->get('status'), ['class' => 'help-block']) ?>
                            </div>
                            <div class="form-group">
                                <?= $this->formLabel($form->get('saturdayenabled')) ?>
                                <?= $this->formElement($form->get('saturdayenabled')) ?>
                                <?= $this->formElementErrors()->render($form->get('saturdayenabled'), ['class' => 'help-block']) ?>
                            </div>
                            <?= $this->form()->closeTag(); ?> 
                        </div>
                        <div class="modal-footer">
                            <!--
                             AJAX Form Submit
                            -->
                            <input type="submit" class="btn btn-default" 
                                   onclick='$.post("/items?customerid=<?= $escaper->escapeHtml($this->customerid) ?>&customername=<?= $escaper->escapeHtml($this->customername) ?>", $("#div_form").serialize(), function (data) {
                                               appendRowToTable(data);
                                           });
                                           return false;' 
                                   value="OK" form="addRowItemsForm">
                            <button id="cancel" class="btn btn-default" data-dismiss="modal">Cancel</button>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="ffm-table-padding" >
                    <table id="customerlisttable" class="table table-striped table-bordered nowrap" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Product</th>
                                <th>Description</th>
                                <th>Comment</th>
                                <th>Option</th>
                                <th>Qty</th>
                                <th>Wholesale</th>
                                <th>Retail</th>
                                <th>Override Price</th>
                                <th>UOM</th>
                                <th>SKU</th>
                                <th>Status</th>
                                <th>Saturday Enabled</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>Product</th>
                                <th>Description</th>
                                <th>Comment</th>
                                <th>Option</th>
                                <th>Qty</th>
                                <th>Wholesale</th>
                                <th>Retail</th>
                                <th>Override Price</th>
                                <th>UOM</th>
                                <th>SKU</th>
                                <th>Status</th>
                                <th>Saturday Enabled</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>