<?php

use Zend\Escaper\Escaper;

$escaper = new Escaper('utf-8');
$form = $this->form;
$form->prepare();
?>
<script>
    //#############################################################
    //#############################################################
    //##
    //##    Read data customerid into javascript context, taking
    //##    care to escape the value - just in case ;).
    //##
    //#############################################################
    //#############################################################
    var php_var = "<?= $escaper->escapeHtml($this->customerid) ?>";

    //#############################################################
    //#############################################################
    //##
    //##    Datatables API reference scoped for top-level access. 
    //##
    //#############################################################
    //#############################################################
    var $API;

    var deleteMe = function (e) {
        var sku = $(e.target).attr('data-sku-number');
        var idx = $(e.target).attr('data-index-number');
        console.log('SKU: ' + sku + ' Idx: ' + idx);
        $.getJSON('ajax/items?action=removeRow&sku=' + sku + '&customerid=' + php_var, function () {
            console.log("REST Call made.");
        }).done(function () {
            console.log('Ajax call successful with sku: ' + sku);
            $API.row(idx).remove().draw();
            $('.modal').modal('hide');
        }).fail(function () {
            console.log("REST Call failed.");
        });
    };

    //#############################################################
    //#############################################################
    //##
    //##    Convenience function to get a human readable date string.
    //##
    //#############################################################
    //#############################################################
    var getPrettyTime = function () {
        var objToday = new Date(),
                weekday = new Array('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'),
                dayOfWeek = weekday[objToday.getDay()],
                domEnder = function () {
                    var a = objToday;
                    if (/1/.test(parseInt((a + "").charAt(0))))
                        return "th";
                    a = parseInt((a + "").charAt(1));
                    return 1 === a ? "st" : 2 === a ? "nd" : 3 === a ? "rd" : "th"
                }(),
                dayOfMonth = today + (objToday.getDate() < 10) ? '0' + objToday.getDate() + domEnder : objToday.getDate() + domEnder,
                months = new Array('January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'),
                curMonth = months[objToday.getMonth()],
                curYear = objToday.getFullYear(),
                curHour = objToday.getHours() > 12 ? objToday.getHours() - 12 : (objToday.getHours() < 10 ? "0" + objToday.getHours() : objToday.getHours()),
                curMinute = objToday.getMinutes() < 10 ? "0" + objToday.getMinutes() : objToday.getMinutes(),
                curSeconds = objToday.getSeconds() < 10 ? "0" + objToday.getSeconds() : objToday.getSeconds(),
                curMeridiem = objToday.getHours() > 12 ? "PM" : "AM";
        var today = curHour + ":" + curMinute + "." + curSeconds + curMeridiem + " " + dayOfWeek + " " + dayOfMonth + ", " + curMonth + " " + curYear;
        return today;
    };

    //#############################################################
    //#############################################################
    //##
    //##    OverridePrice button click handler.
    //##    Sends REST GET to Ajax Endpoint. The Endpoint
    //##    inserts the override price record into the db
    //##    and returns the results - which we grab on callback
    //##    and populate the table with the values that were submitted. 
    //##
    //#############################################################
    //#############################################################
    var submitOverride = function (rowIdx, sku) {
        var overrideprice = $('#overrideprice').val();
        var comment = $('[name="comment"]').val();
        var option = $('[name="option"]').val();
        $.getJSON("ajax/items?customerid=<?= $escaper->escapeHtml($this->customerid) ?>&customername=<?= $escaper->escapeHtml($this->customername) ?>&action=overridePrice&index=" + rowIdx + "&sku=" + sku + "&overrideprice=" + overrideprice + "&comment=" + comment + "&option=" + option + "", function (data) {
            overrideCallback(data);
        });
        return false;
    };

    var initForm = function () {
        if ($("#override_form").length) {
            $("#override_form").validate({
                submitHandler: function (form) {
                    var rowIdx = $('#override_form_submit').attr('data-ffm-row-index');
                    var sku = $('#override_form_submit').attr('data-ffm-sku');
                    submitOverride(rowIdx, sku);
                    return false;
                }
            });
        } else {
            console.log('No DIV!');
        }
    };

    //#############################################################
    //#############################################################
    //##
    //##    Callback on Successful Ajax Call to add a row to the table.
    //##
    //#############################################################
    //#############################################################
    var appendRowToTable = function (data) {
        if (data.success) {
            $API.row.add({
                "productname": data['productname'],
                "shortescription": data['shortescription'],
                "comment": data['comment'],
                "option": data['option'],
                "qty": data['qty'],
                "wholesale": data['wholesale'],
                "retail": data['retail'],
                "overrideprice": data['overrideprice'],
                "uom": data['uom'],
                "sku": data['sku'],
                "status": data['status'] === '1' ? 'Enabled' : 'Disabled',
                "saturdayenabled": data['saturdayenabled'] === '1' ? 'Enabled' : 'Disabled'
            }).draw(false);
            //remove values from the form.
            $('[name="product"]').val('');
            $('[name="description"]').val('');
            $('[name="comment"]').val('');
            $('[name="option"]').val('');
            $('[name="qty"]').val('');
            $('[name="wholesale"]').val('');
            $('[name="retail"]').val('');
            $('[name="overrideprice"]').val('');
            $('[name="uom"]').val('');
            $('[name="sku"]').val('');
            //default status to true
            $('[name="status" type="hidden"]').val('1');
            $('[name="status" type="checkbox"]').val('1').attr('checked', 'checked');
            //default saturdayenabled to false
            $('[name="saturdayenabled" type="checkbox"]').removeAttr('checked');
            $('[name="saturdayenabled" type="checkbox"]').val('0');

            return false;
        } else {
            console.log('Row NOT added response: ' + JSON.stringify(data));
        }
    };

    var wrapModal = function (row, rowIdx) {
        var wrapper = ' <div id="detailRowModal" class="modal fade dtr-bs-modal in" role="dialog" style="display: block; padding-left: 0px;">\n\
                            <div class="modal-dialog" role="document">\n\
                                <div class="modal-content">\n\
                                    <div class="modal-header">\n\
                                        <h4 class="modal-title">\n\
                                            ' + generateDetailsModalHeader(row) + '\n\
                                        </h4>\n\
                                    </div>\n\
                                <div class="modal-body">\n\
                                ' + generateDetailsModalBody(rowIdx, row.data()) + '\n\
                                </div>\n\
                            </div>\n\
                        </div>';
        return wrapper;
    };

    var generateDetailsModalHeader = function (row) {
        var data = row.data();
        return data['productname'] + ' <div class="pull-right"><small ><span class="glyphicon glyphicon-barcode" aria-hidden="true"></span> <span >' + data['sku'] + '</span></small><span><button type="button" class="close" data-dismiss="modal">&times;</button></span></div>';
    };

    var generateDetailsModalBody = function (rowIdx, columns) {
        var comment = columns.comment;
        var option = columns.option;
        var qty = columns.qty;
        var wholesale = columns.wholesale;
        var retail = columns.retail;
        var overrideprice = columns.overrideprice;
        var uom = columns.uom;
        var sku = columns.sku;
        var status = columns.status;
        var saturdayenabled = columns.saturdayenabled;
        var data = '';
        var copy = '<div class="row">\n\
                                        <div class="col-md-12">\n\
                                            <hr/>\n\
                                        </div>\n\
                                    </div>';
        if ((comment && comment.length) ||
                (option && option.length)) {
            copy += '   <div class="row">\n\
                                        <div class="col-md-12">\n\
                                            <div class="table-responsive">\n\
                                                <table class="table">\n\
                                                    <thead>\n\
                                                        <tr>\n\
                                                            <th>Comment</th>\n\
                                                            <th>Option</th>\n\
                                                        </tr>\n\
                                                    </thead>\n\
                                                    <tbody>\n\
                                                        <tr>\n\
                                                            <td style="width: 50%;">' + comment + '</td>\n\
                                                            <td style="width: 50%;">' + option + '</td>\n\
                                                        <tr>\n\
                                                    </tbody>\n\
                                                </table>\n\
                                            </div>\n\
                                        </div>\n\
                                    </div>';
        }
        copy += '   <div class="row">\n\
                                        <div class="col-md-12">\n\
                                            <div class="table-responsive">\n\
                                                <table class="table">\n\
                                                    <thead>\n\
                                                        <tr>\n\
                                                            <th>Wholesale</th>\n\
                                                            <th>Retail</th>\n\
                                                            <th>Override Price</th>\n\
                                                        </tr>\n\
                                                    </thead>\n\
                                                    <tbody>\n\
                                                        <tr>\n\
                                                            <td style="width: 33%;">' + wholesale + '</td>\n\
                                                            <td style="width: 33%;">' + retail + '</td>\n\
                                                            <td style="width: 33%;">' + overrideprice + '</td>\n\
                                                        <tr>\n\
                                                    </tbody>\n\
                                                </table>\n\
                                            </div>\n\
                                        </div>\n\
                                    </div>';

        copy += '   <div class="row">\n\
                                        <div class="col-md-12">\n\
                                            <div class="table-responsive">\n\
                                                <table class="table">\n\
                                                    <thead>\n\
                                                        <tr>\n\
                                                            <th>Qty</th>\n\
                                                            <th>UOM</th>\n\
                                                            <th>Saturday</th>\n\
                                                        </tr>\n\
                                                    </thead>\n\
                                                    <tbody>\n\
                                                        <tr>\n\
                                                            <td style="width: 33%;">' + qty + '</td>\n\
                                                            <td style="width: 33%;">' + uom + '</td>\n\
                                                            <td style="width: 33%;">' + saturdayenabled + '</td>\n\
                                                        <tr>\n\
                                                    </tbody>\n\
                                                </table>\n\
                                            </div>\n\
                                        </div>\n\
                                    </div>';
        //#############################################################
        //#############################################################
        //##
        //##    IF row.status = Disabled
        //##    Allow Price Override, but warn the Salesperson.
        //##
        //#############################################################
        //#############################################################
        if (status && status === 'Disabled') {
            data += '<div class="row">';
            data += '       <div class="col-md-12">';
            data += '           <div class="ffm-callout ffm-callout-error">\n\
                                                    <h4 >Notice <small class="pull-right">You must call first.</small></h4>\n\
                                                    <hr/>\n\
                                                    <p>\n\
                                                        This item is marked Out Of Stock. Please call for availability.\n\
                                                    </p>\n\
                                                </div>';
            data += '       </div>';
            data += '</div>';
        }
        data += '   <div class="row">';
        data += '       <div class="col-md-12">';
        data += '           <form id="override_form" class="form" novalidate="novalidate">';
        data += '               <div class="row form-group">\n\
                                                    <div class="col-md-4">\n\
                                                        <label for="overrideprice">\n\
                                                            <i>Override Price</i>&nbsp;<span style="color:red;">*</span> \n\
                                                        </label>\n\
                                                    </div>\n\
                                                    <div class="col-md-4">\n\
                                                        <div class="input-group">\n\
                                                            <div class="input-group-addon">$</div>\n\
                                                            <input type="text" class="form-control" id="overrideprice" aria-describedby="priceHelpInline" placeholder="Price">\n\
                                                        </div>\n\
                                                    </div>\n\
                                                    \n\
                                                    <div class="col-md-4">\n\
                                                        <small id="priceHelpInline" class="text-muted"> -- Enter Price Override.</small>\n\
                                                    </div>\n\
                                                </div>';
        data += '               <div class="row form-group">\n\
                                                    <div class="col-md-4">\n\
                                                        <label for="comment">\n\
                                                            Comments\n\
                                                        </label>\n\
                                                    </div>\n\
                                                    <div class="col-md-4">\n\
                                                        <input type="textarea" class="form-control" name="comment" value="' + comment + '" aria-describedby="commentHelpInline" data-rule-maxlength="255" data-msg-maxlength="At most 255 chars for Comment" placeholder="Comments">\n\
                                                    </div>\n\
                                                    \n\
                                                    <div class="col-md-4">\n\
                                                        <small id="commentHelpInline" class="text-muted"> -- Enter/Edit Comment.</small>\n\
                                                    </div>\n\
                                                </div>';
        data += '               <div class="row form-group">\n\
                                                    <div class="col-md-4">\n\
                                                        <label for="option">\n\
                                                            Option\n\
                                                        </label>\n\
                                                    </div>\n\
                                                    <div class="col-md-4">\n\
                                                        <input type="textarea" class="form-control" name="option" value="' + option + '" aria-describedby="optionHelpInline" data-rule-maxlength="255" data-msg-maxlength="At most 255 chars for Option" placeholder="Options">\n\
                                                    </div>\n\
                                                    \n\
                                                    <div class="col-md-4">\n\
                                                        <small id="optionHelpInline" class="text-muted"> -- Enter/Edit Option.</small>\n\
                                                    </div>\n\
                                                </div>';
        data += '               <div class="row form-group">';
        data += '                       <div class="col-md-4 col-md-offset-4">\n\
                                                            <span class="pull-right">';
        //#############################################################
        //#############################################################
        //##
        //##    Override Price Click Handler.
        //##
        //#############################################################
        //#############################################################
        data += '                                       <button data-toggle="tooltip" title="Press To Delete Product" class="btn btn-danger" onclick="deleteMe(event); return false;" data-sku-number="' + sku + '" data-index-number="' + rowIdx + '">\n\
                                                                    Delete\n\
                                                                </button>\n\
                                                            </span>\n\
                                                        </div>\n\
                                                        <div class="col-md-4">\n\
                                                            <span class="pull-left">\n\
                                                                <button id="override_form_submit" onclick="initForm()" type="submit" data-ffm-row-index="' + rowIdx + '" data-ffm-sku="' + sku + '" \n\
                                                                        data-toggle="tooltip" title="Submit Price Override" class="btn btn-default">\n\
                                                                    Override\n\
                                                                </button>\n\
                                                            </span>\n\
                                                        </div>\n\
                                                </div>';
        data += '           </form>';
        data += '       </div>';
        data += '   </div>';


        //data =+ '';
        return data + copy;
    };

    //#############################################################
    //#############################################################
    //##
    //##    Callback on Successful Ajax Call to override a price.
    //##
    //#############################################################
    //#############################################################
    var overrideCallback = function (data) {
        if (data.success) {
            //price has been successfully overridden into DB
            //now update the values in the table to reflect the override.
            //set the overrideprice on the selected row - then redraw
            //the table to cause the appropriate renderers to handle
            //the override display.
            var rowIdx = data.index;
            var rowData = $API.row(rowIdx).data();
            rowData['overrideprice'] = data.overrideprice;
            rowData['comment'] = data.comment;
            rowData['option'] = data.option;
            $API.row(rowIdx).data(rowData);
            $API.draw(false);
            $('.modal').modal('hide');
        } else {
            console.log('Error occurred trying to overrideprice: ' + JSON.stringify(data));
        }
    };

    //#############################################################
    //#############################################################
    //##
    //##    Document Ready Event Handler
    //##
    //#############################################################
    //#############################################################
    $(document).ready(function () {
        $API = $('#customerlisttable').DataTable({
            "ajax": '/ajax/items?action=customerlisttableget&customerid=' + php_var,
            //#############################################################
            //#############################################################
            //##
            //##    Datatables columnDefs with appropriate renderers.
            //##
            //#############################################################
            //#############################################################
            "columns": [
                {"data": "productname"},
                {"data": "shortescription"},
                {"data": "comment"},
                {"data": "option"},
                {"data": "qty"},
                {"data": "wholesale",
                    "render": function (data, type, row, meta) {
                        if (data) {
                            var result = "$";
                            return result + row['wholesale'];
                        } else {
                            return  '';
                        }
                    }
                },
                {"data": "retail",
                    "render": function (data, type, row, meta) {
                        var enabled = row['status'] === 'Enabled';
                        var hasOverride = row['overrideprice'];
                        if (enabled && data) {
                            var result = "$";
                            return result + row['retail'];
                        } else if (!enabled && !hasOverride) {
                            return  'Call for availability';
                        }
                        return data;
                    }
                },
                {"data": "overrideprice",
                    "render": function (data, type, row, meta) {
                        if (data) {
                            var result = "$";
                            return result + data;
                        } else {
                            return  data;
                        }
                        return data;
                    }
                },
                {"data": "uom"},
                {"data": "sku"},
                {"data": "status",
                    "render": function (data, type, row, meta) {
                        var result = "";
                        if (row['status']) {
                            result = data;
                        } else {
                            result = '<p class="bg-warning">Out of Stock</p>';
                        }
                        return result;
                    }},
                {"data": "saturdayenabled",
                    "render": function (data, type, row, meta) {
                        var result = "";
                        if (row['saturdayenabled']) {
                            result = 'On';
                        } else {
                            result = 'Off';
                        }
                        return result;
                    }
                }
            ],
            //#############################################################
            //#############################################################
            //##
            //##    Datables RowCallback executed on every row.
            //##    Checks if row.status = Enabled OR if 
            //##    row.overrideprice is set - in which case, we
            //##    lift the requirement whereby we grey out every 
            //##    Disabled row because if the overrideprice has a
            //##    value - then the Salesperson has called in and 
            //##    overridden it.
            //##
            //#############################################################
            //#############################################################
            rowCallback: function (row, data, index) {
                if (data.status !== 'Enabled' && !data.overrideprice) {
                    $(row).attr('class', 'ffm-table-disabled');
                }
            },
            //#############################################################
            //#############################################################
            //##
            //##    Datatables Responsive Plugin
            //##
            //#############################################################
            //#############################################################
            responsive: {
                details: {
                    display: $.fn.dataTable.Responsive.display.modal({
                        header: function (row) {
                            return generateDetailsModalHeader(row);
                        }
                    }),
                    renderer: function (api, rowIdx, columns) {
                        //handle case where item is disabled!
                        return generateDetailsModalBody(rowIdx, columns, false);
                    },
                    type: 'column',
                    target: 'none'
                }
            },
            dom: 'Bfrtip',
            //#############################################################
            //#############################################################
            //##
            //##    Datatables Buttons Plugin.
            //##    pdfHtml5 Button creates PDF.
            //##    add-row Button allows Salesperson to add a row to 
            //##    the table.
            //##
            //#############################################################
            //#############################################################
            buttons: [
                {
                    extend: 'pdfHtml5',
                    orientation: 'landscape',
                    pageSize: 'LEGAL',
                    customize: function (doc) {
                        var form_data = new Array();
                        doc.content.forEach(function (row) {
                            if (row['table'] && row['table']['body']) {
                                var newRowData = [];
                                var idx = 0;
                                row['table']['body'].forEach(function (rowdata) {
                                    //product,  description, comments, UOM, SKU, Retail price or Inserted price.
                                    //remove idx: 3-7
                                    if (idx++ === 0) {
                                        //add our customized Header Row.
                                        var head = JSON.parse('[{"text": "Product","style": "tableHeader"}, {"text": "Description","style": "tableHeader"}, {"text": "Comment","style": "tableHeader"}, {"text": "UOM","style": "tableHeader"}, {"text": "SKU","style": "tableHeader"}, {"text": "Price","style": "tableHeader"}]');
                                        newRowData.push(head);
                                    } else {
                                        var tablerow = $API.row(idx).data();
                                        if (tablerow)
                                            form_data.push('ID_' + tablerow['id'], JSON.stringify(tablerow));
                                        var row = [];
                                        row.push(rowdata[0]);
                                        row.push(rowdata[1]);
                                        row.push(rowdata[2]);
                                        row.push(rowdata[8]);
                                        row.push(rowdata[9]);
                                        var override = rowdata[7].text;
                                        if (override) {
                                            row.push(rowdata[7]);
                                        } else {
                                            row.push(rowdata[6]);
                                        }

                                        //only add this row if Price
                                        if (override || rowdata[6].text.indexOf('Call') === -1) {
                                            newRowData.push(row);
                                        }
                                    }
                                });
                                row['table']['body'] = newRowData;
                            }
                        });
                        //doc.content.body.table.widths = [ '*', 'auto', 100, '*' ];

                        var today = getPrettyTime();
                        doc.content.splice(1, 0, {
                            margin: [0, 0, 0, 20],
                            alignment: 'center',
                            //add User's name to report.
                            text: 'Creator: <?= $this->salesperson ?> (<?= $this->salespersonid ?>)     Customer: <?= $this->customername ?> (<?= $this->customerid ?>)      ' + today
                        });

                        var rep = '*';
                        doc.content[2].table.widths = [rep, rep, rep, rep, rep, rep];
                        //alert(JSON.stringify(doc.styles));
                        doc.styles.tableHeader.alignment = 'left';
                        //doc.content[2].table.widths = [ '100%'];
                        var out = new Array();
                        for (var key in form_data) {
                            out.push(key + '=' + encodeURIComponent(form_data[key]));
                        }
                        var outdata = out.join('&');
                        $.ajax({
                            url: 'items/report?customerid=' + php_var,
                            type: 'POST',
                            data: outdata,
                            contentType: 'application/x-www-form-urlencoded',
                            success: function (data) {
                                console.log('Successful response from server at items/report');
                                console.log(JSON.stringify(data));
                            },
                            error: function (xhr, ajaxOptions, thrownError) {
                                alert(xhr.status);
                                alert(thrownError);
                            }
                        });
                    }
                },
                {
                    text: 'Add Product',
                    className: 'ffm-custom-append'
                }
            ]
        });
        //#############################################################
        //#############################################################
        //##
        //##    REMOVE Table Row.
        //##    Remove button added to each table row. 
        //##    Removes the row after sending an AJAX GET call 
        //##    with query params specifying customerid and
        //##    sku and action. Then the AbstractRestful ItemsController
        //##    Endpoint handles the request and adds the removedSKU
        //##    to session scope [customerid][removedSKUS]=[$skus1Dim]
        //##    so even if the Salesperson navigates to other customers
        //##    and prints other PDF's, as long as they stay logged-in
        //##    and do not press the logout button -> The removed rows
        //##    are always respected and override the svc GET calls.
        //##    @see \Ajax\Service\Sales\ItemsFilterTableArrayService.
        //##
        //#############################################################
        //#############################################################
        $('body').on('click', '.deleteMe', function () {
            //first make ajax call to ItemsController to add the removedSKU to session
            //then remove the row and call draw after the call returns

            //Component markup must have sku and index data attributes like so:
            //<button class="btn btn-danger deleteMe" data-sku-number="123456" data-index-number="0">
            //  <span class="glyphicon glyphicon-minus">
            //  </span>
            //</button>

            var sku = $(this).attr('data-sku-number');
            var idx = $(this).attr('data-index-number');
            console.log('SKU: ' + sku + ' Idx: ' + idx);
            $.getJSON('ajax/items?action=removeRow&sku=' + sku + '&customerid=' + php_var, function () {
                console.log("REST Call made.");
            }).done(function () {
                console.log('Ajax call successful with sku: ' + sku);
                $API.row(idx).remove().draw();
                $('.modal').modal('hide');
            }).fail(function () {
                console.log("REST Call failed.");
            });
        });

        $("#customerlisttable").on('click', 'tbody tr', function (e) {
            $('#detailRowModal').remove();
            var idx = $(this).index();
            var row = $API.row(idx);
            //alert(JSON.stringify(row.data()));
            var modal = wrapModal(row, idx);
            console.log('Showing Modal!');
            $('footer').after($(modal).modal('show'));
        });


        //#############################################################
        //#############################################################
        //##
        //##    INIT Function called after itemsTable.draw();
        //##    This will add necessary data-*-attr's for the
        //##    ffm-custom-append Button added to the Datatables
        //##    options.
        //##
        //#############################################################
        //#############################################################
        $API.on('init.dt', function (e, settings, json) {
            //##########  Custom Datatables Buttons Impl ##############
            //this is used to add data-* attributes to datatables buttons.
            //the button is initialized
            var api = new $.fn.dataTable.Api(settings);
            if (api.buttons().length > 0) {
                $("a", api.buttons().container(0)).each(function (index) {
                    if ($(this).hasClass('ffm-custom-append')) {
                        $(this).attr('data-target', '#addProductModal');
                        $(this).attr('data-toggle', 'modal');
                    }
                });
            }
            //##########  END Custom Datatables Buttons Impl ##############
        });

        $("[name='addRowItemsForm']").validate({
            submitHandler: function (form) {
                $.ajax({
                    type: 'POST',
                    url: "https://pricing.localhost/items?customerid=<?= $escaper->escapeHtml($this->customerid) ?>&customername=<?= $escaper->escapeHtml($this->customername) ?>",
                    data: $(form).serialize()
                })
                        .done(function (response) {
                            if (response.success) {
                                appendRowToTable(response);
                            } else {
                                alert('Error - Please contact IT.');
                            }
                        });
                return false;
            }
        });

    });

</script>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            &nbsp;
        </div>
        <div class="col-md-12">
            <nav class="breadcrumb">
                <?php if (isset($_SESSION["roles"])): ?>
                    <?php if ($_SESSION["roles"][0]->getRole() == "admin"): ?>
                        <?php if (isset($_SESSION["salespersoninplay"])): ?>
                                <li>
                                    <a href="/sales"><?= $_SESSION["salespersoninplay"]->getSalespersonname() ?></a>
                                </li>
                        <?php else: ?>
                            <li>
                                <a href="/sales">Salespeople</a>
                            </li>
                        <?php endif; ?>
                    <?php endif; ?>
                <?php endif; ?>
                <li>
                    <a href="/users">
                        <?= $escaper->escapeHtml($this->customername) ?>
                    </a>
                </li>
                <li class="active">Products</li>
            </nav>
            <div class="ffm-callout ffm-callout-warning">
                <h4 >Products <small class="pull-right"><?= $this->customername ?></small></h4>
                <hr/>
                <p>Please make selections for your customer.</p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="modal fade" id="addProductModal" role="dialog">
                <div class="modal-dialog">
                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">Add Product</h4>
                        </div>
                        <div class="modal-body">
                            <?= $this->form()->openTag($form); ?> 
                            <div class="row form-group">
                                <div class="col-md-4">
                                    <?= $this->formlabel($form->get('product')) ?>
                                </div>
                                <div class="col-md-4">
                                    <?= $this->formElement($form->get('product')) ?>
                                </div>
                                <div class="col-md-4">
                                    <small id="productHelpInline" class="text-muted"> -- Enter Product Name.</small>
                                </div>
                            </div>
                            <div class="row form-group">
                                <div class="col-md-4">
                                    <?= $this->formlabel($form->get('description')) ?>
                                </div>
                                <div class="col-md-4">
                                    <?= $this->formElement($form->get('description')) ?>
                                </div>
                                <div class="col-md-4">
                                    <small id="descriptionHelpInline" class="text-muted"> -- Enter Description.</small>
                                </div>
                            </div>
                            <div class="row form-group">
                                <div class="col-md-4">
                                    <?= $this->formlabel($form->get('comment')) ?>
                                </div>
                                <div class="col-md-4">
                                    <?= $this->formElement($form->get('comment')) ?>
                                </div>
                                <div class="col-md-4">
                                    <small id="commentHelpInline" class="text-muted"> -- Enter Comment.</small>
                                </div>
                            </div>
                            <div class="row form-group">
                                <div class="col-md-4">
                                    <?= $this->formlabel($form->get('option')) ?>
                                </div>
                                <div class="col-md-4">
                                    <?= $this->formElement($form->get('option')) ?>
                                </div>
                                <div class="col-md-4">
                                    <small id="optionHelpInline" class="text-muted"> -- Enter Option.</small>
                                </div>
                            </div>
                            <div class="row form-group">
                                <div class="col-md-4">
                                    <?= $this->formlabel($form->get('qty')) ?>
                                </div>
                                <div class="col-md-4">
                                    <?= $this->formElement($form->get('qty')) ?>
                                </div>
                                <div class="col-md-4">
                                    <small id="qtyHelpInline" class="text-muted"> -- Enter Quantity.</small>
                                </div>
                            </div>
                            <div class="row form-group">
                                <div class="col-md-4">
                                    <?= $this->formlabel($form->get('wholesale')) ?>
                                </div>
                                <div class="col-md-4">
                                    <?= $this->formElement($form->get('wholesale')) ?>
                                </div>
                                <div class="col-md-4">
                                    <small id="wholesaleHelpInline" class="text-muted"> -- Enter Wholesale Price.</small>
                                </div>
                            </div>
                            <div class="row form-group">
                                <div class="col-md-4">
                                    <?= $this->formlabel($form->get('retail')) ?>
                                </div>
                                <div class="col-md-4">
                                    <?= $this->formElement($form->get('retail')) ?>
                                </div>
                                <div class="col-md-4">
                                    <small id="retailHelpInline" class="text-muted"> -- Enter Retail Price.</small>
                                </div>
                            </div>
                            <div class="row form-group">
                                <div class="col-md-4">
                                    <?= $this->formlabel($form->get('overrideprice')) ?>
                                </div>
                                <div class="col-md-4">
                                    <?= $this->formElement($form->get('overrideprice')) ?>
                                </div>
                                <div class="col-md-4">
                                    <small id="overridepriceHelpInline" class="text-muted"> -- Enter Override Price.</small>
                                </div>
                            </div>
                            <div class="row form-group">
                                <div class="col-md-4">
                                    <?= $this->formlabel($form->get('uom')) ?>
                                </div>
                                <div class="col-md-4">
                                    <?= $this->formElement($form->get('uom')) ?>
                                </div>
                                <div class="col-md-4">
                                    <small id="uomHelpInline" class="text-muted"> -- Enter Unit of Measure.</small>
                                </div>
                            </div>
                            <div class="row form-group">
                                <div class="col-md-4">
                                    <?= $this->formlabel($form->get('sku')) ?>
                                </div>
                                <div class="col-md-4">
                                    <?= $this->formElement($form->get('sku')) ?>
                                </div>
                                <div class="col-md-4">
                                    <small id="skuHelpInline" class="text-muted"> -- Enter SKU.</small>
                                </div>
                            </div>
                            <div class="row form-group">
                                <div class="col-md-4">
                                    <?= $this->formlabel($form->get('status')) ?>
                                </div>
                                <div class="col-md-4">
                                    <div class="row">
                                        <div class="col-md-3 col-md-offset-9">
                                            <?= $this->formElement($form->get('status')) ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <small id="statusHelpInline" class="text-muted"> -- Check Status.</small>
                                </div>
                            </div>
                            <div class="row form-group">
                                <div class="col-md-4">
                                    <?= $this->formlabel($form->get('saturdayenabled')) ?>
                                </div>
                                <div class="col-md-4">
                                    <div class="row">
                                        <div class="col-md-3 col-md-offset-9">
                                            <?= $this->formElement($form->get('saturdayenabled')) ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <small id="saturdayenabledHelpInline" class="text-muted"> -- Check Saturday Enabled.</small>
                                </div>
                            </div>
                            <?= $this->form()->closeTag(); ?> 
                        </div>
                        <div class="modal-footer">
                            <!--
                             AJAX Form Submit
                            -->
                            <button id="cancel" class="btn btn-danger" data-dismiss="modal">Cancel</button>
                            <input type="submit" class="btn btn-default" 
                                   value="Submit" form="addRowItemsForm">
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="ffm-table-padding" >
                    <table id="customerlisttable" class="table table-striped table-bordered nowrap" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Product</th>
                                <th>Description</th>
                                <th>Comment</th>
                                <th>Option</th>
                                <th>Qty</th>
                                <th>Wholesale</th>
                                <th>Retail</th>
                                <th>Override Price</th>
                                <th>UOM</th>
                                <th>SKU</th>
                                <th>Status</th>
                                <th>Saturday Enabled</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>Product</th>
                                <th>Description</th>
                                <th>Comment</th>
                                <th>Option</th>
                                <th>Qty</th>
                                <th>Wholesale</th>
                                <th>Retail</th>
                                <th>Override Price</th>
                                <th>UOM</th>
                                <th>SKU</th>
                                <th>Status</th>
                                <th>Saturday Enabled</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>