
<div class="login">
    <div class="page-header">
        <h1><?php echo 'Sign in' ?></h1>
    </div>

    <?php
    $form = $this->form;
    $this->headLink()
            ->appendStylesheet($this->basePath() . 'mycss/login.css');
    $form->setAttribute('action', $this->url(
                    'login/process', array(
                'action' => 'authenticate',
                    )
    ));
    $form->setAttribute('class', 'form-signin');
    $form->prepare();
    $formLabel = $this->plugin('formLabel');
    $username = $form->get('username');
    $submit = $form->get('submit');
    $rememberme = $form->get('rememberme');
    $password = $form->get('password');
    ?>

    <?php echo $this->form()->openTag($form) ?>
    <div class="form-group">
        <?php echo $this->formInput($username) ?>                          
    </div>
        <div class="form-group">
        <?php echo $this->formInput($password) ?>                        
    </div>
    <div class="form-group">
        <?php echo $this->formSubmit($submit) ?>                       
    </div>
        
        
        <?php echo $this->form()->closeTag() ?>
        <?php
        if ($this->messages) {
            echo '<ul class="login-list">';
            foreach ($this->messages as $message) {
                echo '<li class="error">' . $message . '</li>';
            }
            echo '</ul>';
        }
        ?>
</div>
