<div class="container">
    <div class="row">
        <div class="col-sm-6 col-md-4 col-md-offset-4">
            <div class="ffm-callout ffm-callout-warning">
                <h4 >Welcome, 
                    <small>
                        <?php echo $_SESSION["user"]->getUsername() ?>
                    </small>
                </h4>
                <hr/>
                <p>
                    You have successfully logged in.
                </p>
            </div>
        </div>
    </div>
</div>