---
  - name: Deploy Pricing (localhost)
    hosts: local
    connection: local
    gather_facts: False
    tags: deployment

    tasks:
        
      - name: Zip pricing
        shell: |
            cd {{ lookup('env','PROJECT_HOME_DIR') }}/
            zip -r pricing.zip pricing/
            
      - name: SCP pricing
        shell: |
            cd /u/local/jasonpalmer/
            scp -i /Users/jasonpalmer/jpalmer.pem pricing.zip root@10.0.5.243:.
            scp -i /Users/jasonpalmer/jpalmer.pem pricing.zip root@10.0.4.172:.
        
# REMOTE
        
  - name: Deploy Pricing (WebServer)
    hosts: webserver
    vars_files:
    - ./vars/pricing_vars.yml
    remote_user: root

    tasks:
        
      - name: Deploy pricing on remote
        shell: |
            cd ~/;sudo unzip pricing.zip
            rm -rf pricing.zip
            cd /vol01/
            sudo rm -rf pricing_archive
            sudo mv pricing pricing_archive
            sudo mv ~/pricing/ /vol01/pricing/
            sudo chown apache:apache -R pricing/*
            sudo chmod a+r,a+w,a+x -R pricing/* 
            sudo rm -rf /vol01/pricing/data/cache/*
            
      - name: insert/update Apache Config
        blockinfile:
          dest: /etc/httpd/conf/httpd.conf
          state: present
          marker: "# {mark} ANSIBLE MANAGED BLOCK PRICING"
          block: "{{ pricing_vhost_block }}"
          
      - name: Restart Apache
        shell: |
            service httpd restart
            
      

