<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
            <?= $this->headTitle('Pricing App')->setSeparator(' - ')->setAutoEscape(false) ?>
            <?=
                    $this->headMeta()
                    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ?>
            <!-- Le styles -->
            <?=
                    $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                    ->prependStylesheet($this->basePath('font-awesome/css/font-awesome.min.css'));
            ?>
            <link rel="stylesheet" type="text/css" href="<?= $this->basePath('css/datatables.cdn.css?eli=1'); ?>"/>
            <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
                <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
                    <script type="text/javascript" src="<?= $this->basePath('js/datatables.cdn.js?eli=1'); ?>"></script>
                    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
                    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
                    <!--[if lt IE 9]>
                        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
                        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
                    <![endif]-->
                    <?= $this->headScript()->prependFile($this->basePath('js/clean-blog.js?eli=1')); ?>
                    <?= $this->headScript()->prependFile($this->basePath('js/jquery.validate.min.js?eli=1')); ?>
                    <?= $this->headScript()->prependFile($this->basePath('js/additional-methods.min.js?eli=1')); ?>
                    <?= $this->headLink()->prependStylesheet($this->basePath('css/style.css?eli=1')); ?>
                    <?= $this->headLink()->prependStylesheet($this->basePath('css/dist/style.css?eli=1')); ?>
                    </head>
                    <body>

                        <nav class="navbar" role="navigation">
                            <div class="container" id="menu">
                                <div class="navbar-header" style="font-weight: 700;text-transform: uppercase;color: #444;">
                                    <img 
                                        src="img/ffm_logo_80x80.png" 
                                        style="width: 65px;"
                                        alt="FFM">
                                        <?php if (isset($this->FFM_SESSION["user"])): ?>
                                            Welcome, <?= $this->FFM_SESSION["user"]->getUsername() ?>
                                        <?php endif; ?>

                                        <h1 class="page-title"><?php echo $this->pageTitle; ?></h1>
                                        
                                </div>
                                <div class="collapse navbar-collapse">
                                    <ul class="nav navbar-nav navbar-right">

                                        <?php if (isset($this->FFM_SESSION["user"]) && count($this->FFM_SESSION["user"]) > 0): ?>
                                            <li>
                                                <a href="<?php echo $this->url('login/process', array('action' => 'logout')); ?>">Logout</a>
                                            </li>
                                        <?php endif; ?>

                                        <?php if (isset($this->FFM_SESSION["roles"]) && count($this->FFM_SESSION["roles"]) > 0): ?>
                                            <?php if ($this->FFM_SESSION["roles"][0]->getRole() == "admin"): ?>
                                                <li>
                                                    <a 
                                                    <?php if (strcmp($this->CURRENT_ROUTE_NAME, "sales") == 0): ?>
                                                            class="ffm-active"
                                                        <?php endif; ?>
                                                        href="<?= $this->url('sales') ?>">Salespeople</a>
                                                </li>
                                            <?php endif; ?>
                                        <?php endif; ?>

                                        <?php if (isset($this->FFM_SESSION["user"])): ?>
                                            <li>
                                                <a 
                                                <?php
                                                if (strcmp($this->CURRENT_ROUTE_NAME, "users") == 0):
                                                    ?>
                                                        class="ffm-active"
                                                    <?php endif; ?>
                                                    href="<?= $this->url('users') ?>">Customers</a>
                                            </li>
                                        <?php endif; ?>


                                    </ul>
                                </div><!-- /.navbar-collapse -->
                                <!-- menu -->
                            </div>
                        </nav>

                        <div id="lazyLoadingOverlay" style="display:none;">
                            <div class="progress">
                                <div class="progress-bar" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width:0%;">
                                </div>
                            </div>
                        </div>
                        <div class="overlay" style="display:none;">
                            <div class="processing-message">
                                <p>Please wait while the system is processing your request...</p>
                                <span class="loader"> </span>
                                <span class="loader2"> </span>
                            </div>
                        </div>

                        <div class="container main">

                            <?= $this->content ?>

                        </div>
                        <footer>
                            <p> <?php echo 'Fulton Fish Market - Pricing App' ?>&nbsp; <?php echo date('Y') ?> Meade Digital Enterprises </p>
                        </footer>
                        <?php
                        //echo '<pre>';
                        //var_dump($_SESSION);
                        //echo '</pre>';
                        ?>
                        <?= $this->inlineScript() ?>
                    </body>
                    </html>
