<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <nav class="breadcrumb">
                <span class="active">Sales</span>
            </nav>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="list-group">
                <?php foreach ($this->json["salespeople"] as $salesperson): ?>
                    <a href="<?php echo $this->url('users', [], array('query' => array('salespersonid' => $salesperson["id"], 'salesperson' => $salesperson["salesperson"]))); ?>" 
                       class="list-group-item list-group-item-action">
                        <span class="my-tag tag tag-grey tag-pill float-xs-right"><?php echo $salesperson["id"]; ?></span>
                        <h5 class="list-group-item-heading"><?php echo $salesperson["salesperson"]; ?></h5>
                    </a>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>