<div class="container">
    <div class="row">
        <div class="col-sm-6 col-md-4 col-md-offset-4">
            <div class="ffm-callout ffm-callout-warning">
                <h4 >Customers</h4>
                <hr/>
                <p>Select one of your customers</p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6 col-md-4 col-md-offset-4">
            <div class="list-group">
                <?php foreach ($this->json["customers"] as $customer): ?>
                    <a href="<?php echo $this->url('items', [], array('query' => array('customerid' => $customer["id"]))); ?>" 
                       class="list-group-item list-group-item-action">
                        <span class="tag tag-grey tag-pill float-xs-right"><?php echo $customer["id"] ?></span>
                        <h5 class="list-group-item-heading"><?php echo $customer["name"] ?> <small><?php echo $customer["company"] ?></small></h5>
                        <h5><?php echo $customer["email"] ?></h5>
                    </a>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>
