<script type="text/javascript">
    $(document).ready(function(){
        $('[data-toggle="tooltip"]').tooltip();
    });
</script>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            &nbsp;
        </div>
        <div class="col-md-12">
            <nav class="breadcrumb">
                <?php if (isset($_SESSION["roles"])): ?>
                    <?php if ($_SESSION["roles"][0]->getRole() == "admin"): ?>
                        <?php if (isset($_SESSION["salespersoninplay"])): ?>
                                <li>
                                    <a data-toggle="tooltip" data-placement="top" title="Click to change selected Salesperson." href="/sales"><?= $_SESSION["salespersoninplay"]->getSalespersonname() ?></a>
                                </li>
                        <?php else: ?>
                            <li>
                                <a data-toggle="tooltip" data-placement="top" title="Click to change selected Salesperson." href="/sales">Salespeople</a>
                            </li>
                        <?php endif; ?>
                    <?php endif; ?>
                <?php endif; ?>
                <li class="active">Customers</li>
            </nav>
            <div class="ffm-callout ffm-callout-warning">
                <h4 >Customers</h4>
                <hr/>
                <p>Select one of your customers</p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="list-group">
                <?php foreach ($this->json["customers"] as $customer): ?>
                    <a href="<?php echo $this->url('items', [], array('query' => array('customerid' => $customer["id"], 'customername' => $customer["name"]))); ?>" 
                       class="list-group-item list-group-item-action">
                        <span class="tag tag-grey tag-pill float-xs-right"><?php echo $customer["id"] ?></span>
                        <h5 class="list-group-item-heading"><?php echo $customer["name"] ?> <small><?php echo $customer["company"] ?></small></h5>
                        <h5><?php echo $customer["email"] ?></h5>
                    </a>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>
